# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schedule_system_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379
    database: 1

# 日志配置
logging:
  level:
    com.meituan.schedule: debug
    org.springframework.web: debug
    org.springframework.security: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

# 开发工具
spring.devtools:
  restart:
    enabled: true
  livereload:
    enabled: true

