# 生产环境配置
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/schedule_system?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}
    database: 0

# 日志配置
logging:
  level:
    com.meituan.schedule: info
    org.springframework.security: warn
    org.hibernate.SQL: warn
  file:
    name: /var/log/schedule-system/application.log
    max-size: 500MB
    max-history: 60

# 安全配置
server:
  ssl:
    enabled: false
  error:
    include-stacktrace: never

